pub(super) enum Command {
    About,
    Cat,
    Cd,
    Clear,
    Cp,
    Contact,
    Echo,
    Editor,
    Empty,
    Exit,
    Greeting,
    Grep,
    Help,
    History,
    Hostname,
    Ls,
    MissingEditor,
    MkDir,
    Mv,
    Pwd,
    Rm,
    RmDir,
    Sudo,
    Theme,
    Unknown,
}

impl From<&str> for Command {
    fn from(value: &str) -> Self {
        use Command::*;
        match value {
            "about" => About,
            "cat" => Cat,
            "cd" => Cd,
            "clear" => Clear,
            "cp" => Cp,
            "contact" => Contact,
            "echo" => Echo,
            "ed" | "emacs" | "nano" => MissingEditor,
            "exit" => Exit,
            "greeting" => Greeting,
            "grep" | "rg" => Grep,
            "help" => Help,
            "history" => History,
            "hostname" => Hostname,
            "ls" | "eza" => Ls,
            "mkdir" => MkDir,
            "mv" => Mv,
            "pwd" => Pwd,
            "rm" => Rm,
            "rmdir" => RmDir,
            "su" | "sudo" => Sudo,
            "theme" => Theme,
            "vi" | "vim" | "nvim" => Editor,
            _ => Unknown,
        }
    }
}
